Vagrant.configure(2) do |config|
  config.vm.define "manager" do |manager|
    manager.vm.box = "bento/ubuntu-24.04"
    manager.vm.network "private_network", ip: "192.168.11.22"
    manager.vm.provision "shell", path: "docker_install.sh"
    manager.vm.hostname = "manager"
    manager.vm.network "forwarded_port", guest: 80, host: 80
    manager.vm.network "forwarded_port", guest: 443, host: 8443
    manager.vm.network "forwarded_port", guest: 8000, host: 8000
    manager.vm.network "forwarded_port", guest: 5000, host: 50000
    manager.vm.network "forwarded_port", guest: 6379, host: 6379
    manager.vm.network "forwarded_port", guest: 2375, host: 2375
    manager.vm.network "forwarded_port", guest: 2376, host: 2376
    manager.vm.network "forwarded_port", guest: 2377, host: 2377
  end
  config.vm.define "worker1" do |worker1|
    worker1.vm.box = "bento/ubuntu-24.04"
    worker1.vm.network "private_network", ip: "192.168.11.33"
    worker1.vm.provision "shell", path: "docker_install.sh"
    worker1.vm.hostname = "worker1"
    worker1.vm.network "forwarded_port", guest: 80, host: 8081
    worker1.vm.network "forwarded_port", guest: 443, host: 8444
    worker1.vm.network "forwarded_port", guest: 8000, host: 8001
    worker1.vm.network "forwarded_port", guest: 5000, host: 5001
    worker1.vm.network "forwarded_port", guest: 6379, host: 6380
    worker1.vm.network "forwarded_port", guest: 2377, host: 23770
  end
  config.vm.define "worker2" do |worker2|
    worker2.vm.box = "bento/ubuntu-24.04"
    worker2.vm.network "private_network", ip: "192.168.11.44"
    worker2.vm.provision "shell", path: "docker_install.sh"
    worker2.vm.hostname = "worker2"
    worker2.vm.network "forwarded_port", guest: 80, host: 8082
    worker2.vm.network "forwarded_port", guest: 443, host: 8445
    worker2.vm.network "forwarded_port", guest: 8000, host: 8002
    worker2.vm.network "forwarded_port", guest: 5000, host: 5002
    worker2.vm.network "forwarded_port", guest: 6379, host: 6381
    worker2.vm.network "forwarded_port", guest: 2377, host: 23771
  end
end