Vagrant.configure(2) do |config|
  config.vm.define "manager" do |manager|
    manager.vm.box = "bento/ubuntu-24.04"
    manager.vm.network "private_network", ip: "192.168.11.22"
    manager.vm.provision "shell", path: "docker_install.sh"
    manager.vm.network "forwarded_port", guest: 80, host: 8080
    manager.vm.network "forwarded_port", guest: 443, host: 8443
    manager.vm.network "forwarded_port", guest: 8000, host: 8000
    manager.vm.network "forwarded_port", guest: 5000, host: 50000
    manager.vm.network "forwarded_port", guest: 6379, host: 6379
    manager.vm.network "forwarded_port", guest: 2375, host: 2375
    manager.vm.network "forwarded_port", guest: 2376, host: 2376
    manager.vm.network "forwarded_port", guest: 2377, host: 2377
    manager.vm.network "forwarded_port", guest: 8080, host: 8080
    manager.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end
  config.vm.define "agent1" do |agent1|
    agent1.vm.box = "bento/ubuntu-24.04"
    agent1.vm.network "private_network", ip: "192.168.11.33"
    agent1.vm.provision "shell", path: "docker_install.sh"
    agent1.vm.network "forwarded_port", guest: 80, host: 8081
    agent1.vm.network "forwarded_port", guest: 443, host: 8444
    agent1.vm.network "forwarded_port", guest: 8000, host: 8001
    agent1.vm.network "forwarded_port", guest: 5000, host: 5001
    agent1.vm.network "forwarded_port", guest: 6379, host: 6380
    agent1.vm.network "forwarded_port", guest: 2377, host: 23770
    agent1.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end
  config.vm.define "agent2" do |agent2|
    agent2.vm.box = "bento/ubuntu-24.04"
    agent2.vm.network "private_network", ip: "192.168.11.44"
    agent2.vm.provision "shell", path: "docker_install.sh"
    agent2.vm.network "forwarded_port", guest: 80, host: 8082
    agent2.vm.network "forwarded_port", guest: 443, host: 8445
    agent2.vm.network "forwarded_port", guest: 8000, host: 8002
    agent2.vm.network "forwarded_port", guest: 5000, host: 5002
    agent2.vm.network "forwarded_port", guest: 6379, host: 6381
    agent2.vm.network "forwarded_port", guest: 2377, host: 23771
    agent2.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end
end